// template/src/renderer/layout/Bootloading.tsx
import { useEffect, useState } from 'react';
import { Progress } from 'antd';
import packageJson from '../../../../package.json';
import logo from '../assets/logo.png';
import { BootloadingProgressing } from '../../types/electron';

type BootloadingProps = {
  children: React.ReactNode;
};

export const Spin: React.FC<BootloadingProgressing> = props => {
  return (
    <div className="flex h-screen flex-col items-center justify-center gap-5">
      <img className="h-32 w-32" src={logo} />

      <h1 className="text-3xl font-bold text-primary-600">{packageJson.productName}</h1>
      <Progress className="w-80" />
    </div>
  );
};

export const Bootloading: React.FC<BootloadingProps> = ({ children }) => {
  const [processing, setProcessing] = useState<BootloadingProgressing>({ progress: 0, title: '' });

  useEffect(() => {
    console.log('Bootloading');
  }, []);

  const getProgress = async (): Promise<BootloadingProgressing> => {
    const result = await window.electron.system.getBootloadProgressing();
    return result;
  };

  useEffect(() => {
    getProgress().then(result => {
      setProcessing(result);
    });

    return window.electron.system.bootloading(value => {
      setProcessing(value);
    });
  }, []);

  return processing.progress != 100 ? <Spin {...processing} /> : <>{children}</>;
};

// src/renderer/layouts/Bootloading.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import packageJson from '../../../package.json'
import logo from '../assets/genLogo/icon.png'
import type { BootloadingProgressing } from '../../types/electron'

const processing = ref<BootloadingProgressing>({ progress: 0, title: '' })
const loading = ref(true)

onMounted(() => {
  console.log('Bootloading')

  window.electron.system.getBootloadProgressing().then((result: unknown) => {
    console.log('Bootload progress result:', JSON.stringify(result))
    processing.value = result as BootloadingProgressing
  })

  window.electron.system.bootloading((value: unknown) => {
    console.log('Bootload event received:', JSON.stringify(value))
    processing.value = value as BootloadingProgressing
    if ((value as BootloadingProgressing).progress >= 100) {
      loading.value = false
    }
  })
})
</script>

<template>
  <template v-if="loading && processing.progress < 100">
    <div class="flex h-screen flex-col items-center justify-center gap-5">
      <img class="h-32 w-32" :src="logo" />
      <h1 class="text-3xl font-bold text-primary-600">{{ packageJson.productName }}</h1>
      <el-progress class="w-80" :percentage="processing.progress" />
    </div>
  </template>
  <slot v-else />
</template>
