// src/renderer/pages/Home.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import logo from '../assets/genLogo/icon.png'

const router = useRouter()
const { t } = useI18n()

const features = [
  { title: t('homepage.features.zeroConfigIpc.title'), desc: t('homepage.features.zeroConfigIpc.desc') },
  { title: t('homepage.features.autoUpdate.title'), desc: t('homepage.features.autoUpdate.desc') },
  { title: t('homepage.features.themeSystem.title'), desc: t('homepage.features.themeSystem.desc') },
  { title: t('homepage.features.localDatabase.title'), desc: t('homepage.features.localDatabase.desc') },
  { title: t('homepage.features.systemTray.title'), desc: t('homepage.features.systemTray.desc') },
  { title: t('homepage.features.hotReload.title'), desc: t('homepage.features.hotReload.desc') },
  { title: t('homepage.features.bootLoading.title'), desc: t('homepage.features.bootLoading.desc') },
  { title: t('homepage.features.framelessWindow.title'), desc: t('homepage.features.framelessWindow.desc') },
  { title: t('homepage.features.i18nSupport.title'), desc: t('homepage.features.i18nSupport.desc') },
]

const techStack = ['Electron 36', 'Vite 7', 'Vue 3', 'TypeScript', 'Tailwind CSS', 'Element Plus', 'TypeORM', 'better-sqlite3', 'electron-updater', 'vue-i18n']
</script>

<template>
  <div class="h-full overflow-auto bg-gradient-to-br from-slate-50 to-blue-50 p-8 dark:from-[#0f0f1a] dark:to-[#1a1a2e]">
    <div class="mx-auto max-w-6xl space-y-8">
      <!-- About Link -->
      <div class="flex justify-end">
        <el-button @click="router.push('/about')">
          {{ t('common.about') }}
        </el-button>
      </div>

      <!-- Hero Section -->
      <div class="text-center">
        <div class="mb-4 inline-flex items-center gap-3">
          <img :src="logo" alt="Logo" class="h-16 w-16 object-contain drop-shadow-lg" />
        </div>
        <h1 class="mb-2 text-4xl font-bold dark:text-white">{{ t('homepage.title') }}</h1>
        <p class="mb-6 text-lg text-gray-600 dark:text-gray-400">{{ t('homepage.subtitle') }}</p>
      </div>

      <el-divider />

      <!-- Quick Start + IPC -->
      <div class="grid gap-6 md:grid-cols-2">
        <el-card class="overflow-hidden rounded-xl border-none dark:!bg-[#16162a]">
          <template #header>
            <span class="flex items-center gap-2">{{ t('homepage.quickStart.title') }}</span>
          </template>
          <div class="space-y-3 font-mono text-sm">
            <div class="rounded-lg bg-gray-100 p-3 dark:bg-gray-800">
              <el-text class="text-text-secondary"># {{ t('homepage.quickStart.installDeps') }}</el-text><br />
              <el-tag>npm install</el-tag>
            </div>
            <div class="rounded-lg bg-gray-100 p-3 dark:bg-gray-800">
              <el-text class="text-text-secondary"># {{ t('homepage.quickStart.startDev') }}</el-text><br />
              <el-tag>npm start</el-tag>
            </div>
            <div class="rounded-lg bg-gray-100 p-3 dark:bg-gray-800">
              <el-text class="text-text-secondary"># {{ t('homepage.quickStart.buildProd') }}</el-text><br />
              <el-tag>npm run build</el-tag>
            </div>
            <div class="rounded-lg bg-gray-100 p-3 dark:bg-gray-800">
              <el-text class="text-text-secondary"># {{ t('homepage.quickStart.package') }}</el-text><br />
              <el-tag>npm run package</el-tag>
            </div>
          </div>
        </el-card>

        <el-card class="overflow-hidden rounded-xl border-none dark:!bg-[#16162a]">
          <template #header>
            <span class="flex items-center gap-2">{{ t('homepage.ipc.title') }}</span>
          </template>
          <div class="space-y-2 font-mono text-xs">
            <el-text class="text-text-secondary">// {{ t('homepage.ipc.step1') }}</el-text>
            <div class="rounded bg-gray-100 p-2 dark:bg-gray-800">
              <el-tag type="info">src/main/ipc/user/get.ipc.ts</el-tag>
            </div>
            <el-text class="text-text-secondary">// {{ t('homepage.ipc.step2') }}</el-text>
            <div class="rounded bg-gray-100 p-2 dark:bg-gray-800">
              <el-tag type="info">export default async (id: string) =&gt; {</el-tag><br />
              <el-tag type="info">&nbsp;&nbsp;return await db.findOne(id);</el-tag><br />
              <el-tag type="info">}</el-tag>
            </div>
            <el-text class="text-text-secondary">// {{ t('homepage.ipc.step3') }}</el-text>
            <div class="rounded bg-gray-100 p-2 dark:bg-gray-800">
              <el-tag type="info">npm run ipc:sync</el-tag>
            </div>
            <el-text class="text-text-secondary">// {{ t('homepage.ipc.step4') }}</el-text>
            <div class="rounded bg-gray-100 p-2 dark:bg-gray-800">
              <el-tag type="info">const user = await window.electron.user.get('123');</el-tag>
            </div>
          </div>
        </el-card>
      </div>

      <!-- Built-in Features -->
      <el-card class="overflow-hidden rounded-xl border-none dark:!bg-[#16162a]">
        <template #header>
          <span class="flex items-center gap-2 text-xl">{{ t('homepage.features.title') }}</span>
        </template>
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <div
            v-for="(feature, index) in features"
            :key="index"
            class="flex items-start gap-3 rounded-lg bg-gray-50 p-4 transition-all hover:bg-gray-100 dark:bg-gray-800/50 dark:hover:bg-gray-800"
          >
            <div>
              <el-text tag="strong" class="block dark:text-white">{{ feature.title }}</el-text>
              <el-text class="text-text-secondary" size="small">{{ feature.desc }}</el-text>
            </div>
          </div>
        </div>
      </el-card>

      <!-- Project Structure + Tech Stack -->
      <div class="grid gap-6 md:grid-cols-2">
        <el-card class="overflow-hidden rounded-xl border-none dark:!bg-[#16162a]">
          <template #header>
            <span class="flex items-center gap-2">{{ t('homepage.projectStructure.title') }}</span>
          </template>
          <div class="font-mono text-sm">
            <div class="space-y-1 text-gray-700 dark:text-gray-300">
              <div><el-tag type="info">src/</el-tag></div>
              <div class="pl-4">
                <el-tag>├── main/</el-tag>
                <el-text class="text-text-secondary"> # {{ t('homepage.projectStructure.mainProcess') }}</el-text>
              </div>
              <div class="pl-8">
                <el-tag type="info">│ ├── ipc/</el-tag>
                <el-text class="text-text-secondary"> # {{ t('homepage.projectStructure.ipcHandlers') }}</el-text>
              </div>
              <div class="pl-8">
                <el-tag type="info">│ ├── services/</el-tag>
                <el-text class="text-text-secondary"> # {{ t('homepage.projectStructure.services') }}</el-text>
              </div>
              <div class="pl-8">
                <el-tag type="info">│ └── database/</el-tag>
                <el-text class="text-text-secondary"> # {{ t('homepage.projectStructure.database') }}</el-text>
              </div>
              <div class="pl-4">
                <el-tag type="info">├── preload/</el-tag>
                <el-text class="text-text-secondary"> # {{ t('homepage.projectStructure.preload') }}</el-text>
              </div>
              <div class="pl-4">
                <el-tag type="info">├── renderer/</el-tag>
                <el-text class="text-text-secondary"> # {{ t('homepage.projectStructure.renderer') }}</el-text>
              </div>
              <div class="pl-4">
                <el-tag type="info">└── shared/</el-tag>
                <el-text class="text-text-secondary"> # {{ t('homepage.projectStructure.shared') }}</el-text>
              </div>
            </div>
          </div>
        </el-card>

        <el-card class="overflow-hidden rounded-xl border-none dark:!bg-[#16162a]">
          <template #header>
            <span class="flex items-center gap-2">{{ t('homepage.techStack.title') }}</span>
          </template>
          <div class="flex flex-wrap gap-2">
            <el-tag
              v-for="(tech, index) in techStack"
              :key="index"
              type="primary"
              effect="plain"
            >
              {{ tech }}
            </el-tag>
          </div>
          <el-divider class="!my-4" />
          <div class="text-sm text-gray-600 dark:text-gray-400">
            <p class="mb-2">{{ t('homepage.techStack.description1') }}</p>
            <p class="mb-0">{{ t('homepage.techStack.description2') }}</p>
          </div>
        </el-card>
      </div>

      <!-- Footer -->
      <div class="text-center text-sm text-gray-500 dark:text-gray-400">
        <el-text class="text-text-secondary">{{ t('common.madeWith') }}</el-text>
      </div>
    </div>
  </div>
</template>

// src/renderer/pages/Home/Home.tsx
import React from 'react';
import { Typography, Card, Button, Divider } from 'antd';
import {
  InfoCircleOutlined,
  RocketOutlined,
  ThunderboltOutlined,
  DatabaseOutlined,
  SkinOutlined,
  ReloadOutlined,
  LoadingOutlined,
  AppstoreOutlined,
  GlobalOutlined,
  CodeOutlined,
  FolderOutlined,
  ToolOutlined,
} from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import logo from '../../assets/genLogo/icon.png';

const { Title, Text, Paragraph } = Typography;

/**
 * Home - Template documentation and feature showcase
 */
export const Home: React.FC = () => {
  const navigate = useNavigate();
  const { t } = useTranslation();

  const features = [
    {
      icon: <ThunderboltOutlined className="text-2xl text-blue-500" />,
      title: t('homepage.features.zeroConfigIpc.title'),
      desc: t('homepage.features.zeroConfigIpc.desc'),
    },
    {
      icon: <RocketOutlined className="text-2xl text-green-500" />,
      title: t('homepage.features.autoUpdate.title'),
      desc: t('homepage.features.autoUpdate.desc'),
    },
    {
      icon: <SkinOutlined className="text-2xl text-purple-500" />,
      title: t('homepage.features.themeSystem.title'),
      desc: t('homepage.features.themeSystem.desc'),
    },
    {
      icon: <DatabaseOutlined className="text-2xl text-orange-500" />,
      title: t('homepage.features.localDatabase.title'),
      desc: t('homepage.features.localDatabase.desc'),
    },
    {
      icon: <AppstoreOutlined className="text-2xl text-cyan-500" />,
      title: t('homepage.features.systemTray.title'),
      desc: t('homepage.features.systemTray.desc'),
    },
    {
      icon: <ReloadOutlined className="text-2xl text-pink-500" />,
      title: t('homepage.features.hotReload.title'),
      desc: t('homepage.features.hotReload.desc'),
    },
    {
      icon: <LoadingOutlined className="text-2xl text-indigo-500" />,
      title: t('homepage.features.bootLoading.title'),
      desc: t('homepage.features.bootLoading.desc'),
    },
    {
      icon: <ToolOutlined className="text-2xl text-teal-500" />,
      title: t('homepage.features.framelessWindow.title'),
      desc: t('homepage.features.framelessWindow.desc'),
    },
    {
      icon: <GlobalOutlined className="text-2xl text-amber-500" />,
      title: t('homepage.features.i18nSupport.title'),
      desc: t('homepage.features.i18nSupport.desc'),
    },
  ];

  const techStack = [
    'Electron 36',
    'Vite 7',
    'React 19',
    'TypeScript',
    'Tailwind CSS',
    'Ant Design',
    'TypeORM',
    'better-sqlite3',
    'electron-updater',
    'i18next',
  ];

  return (
    <div className="h-full overflow-auto bg-gradient-to-br from-slate-50 to-blue-50 p-8 dark:from-[#0f0f1a] dark:to-[#1a1a2e]">
      <div className="mx-auto max-w-6xl space-y-8">
        {/* About Link - Top Right */}
        <div className="flex justify-end">
          <Button
            type="default"
            icon={<InfoCircleOutlined />}
            onClick={() => navigate('/about')}
            className="flex items-center"
          >
            {t('common.about')}
          </Button>
        </div>

        {/* Hero Section */}
        <div className="text-center">
          <div className="mb-4 inline-flex items-center gap-3">
            <img src={logo} alt="Logo" className="h-16 w-16 object-contain drop-shadow-lg" />
          </div>
          <Title level={1} className="mb-2 !text-4xl dark:!text-white">
            {t('homepage.title')}
          </Title>
          <Paragraph className="!mb-6 text-lg text-gray-600 dark:text-gray-400">{t('homepage.subtitle')}</Paragraph>
        </div>

        <Divider />

        {/* Quick Start + IPC Communication */}
        <div className="grid gap-6 md:grid-cols-2">
          {/* Quick Start */}
          <Card
            title={
              <span className="flex items-center gap-2">
                <RocketOutlined /> {t('homepage.quickStart.title')}
              </span>
            }
            className="overflow-hidden rounded-xl border-none shadow-lg dark:!bg-[#16162a]"
          >
            <div className="space-y-3 font-mono text-sm">
              <div className="rounded-lg bg-gray-100 p-3 dark:bg-gray-800">
                <Text type="secondary"># {t('homepage.quickStart.installDeps')}</Text>
                <br />
                <Text code>npm install</Text>
              </div>
              <div className="rounded-lg bg-gray-100 p-3 dark:bg-gray-800">
                <Text type="secondary"># {t('homepage.quickStart.startDev')}</Text>
                <br />
                <Text code>npm start</Text>
              </div>
              <div className="rounded-lg bg-gray-100 p-3 dark:bg-gray-800">
                <Text type="secondary"># {t('homepage.quickStart.buildProd')}</Text>
                <br />
                <Text code>npm run build</Text>
              </div>
              <div className="rounded-lg bg-gray-100 p-3 dark:bg-gray-800">
                <Text type="secondary"># {t('homepage.quickStart.package')}</Text>
                <br />
                <Text code>npm run package</Text>
              </div>
            </div>
          </Card>

          {/* IPC Communication */}
          <Card
            title={
              <span className="flex items-center gap-2">
                <CodeOutlined /> {t('homepage.ipc.title')}
              </span>
            }
            className="overflow-hidden rounded-xl border-none shadow-lg dark:!bg-[#16162a]"
          >
            <div className="space-y-2 font-mono text-xs">
              <Text type="secondary">{`// ${t('homepage.ipc.step1')}`}</Text>
              <div className="rounded bg-gray-100 p-2 dark:bg-gray-800">
                <Text code className="!text-blue-600">
                  src/main/ipc/user/get.ipc.ts
                </Text>
              </div>
              <Text type="secondary">{`// ${t('homepage.ipc.step2')}`}</Text>
              <div className="rounded bg-gray-100 p-2 dark:bg-gray-800">
                <Text code>{`export default async (id: string) => {`}</Text>
                <br />
                <Text code>{`  return await db.findOne(id);`}</Text>
                <br />
                <Text code>{`}`}</Text>
              </div>
              <Text type="secondary">{`// ${t('homepage.ipc.step3')}`}</Text>
              <div className="rounded bg-gray-100 p-2 dark:bg-gray-800">
                <Text code>npm run ipc:sync</Text>
              </div>
              <Text type="secondary">{`// ${t('homepage.ipc.step4')}`}</Text>
              <div className="rounded bg-gray-100 p-2 dark:bg-gray-800">
                <Text code>{`const user = await window.electron.user.get('123');`}</Text>
              </div>
            </div>
          </Card>
        </div>

        {/* Built-in Features */}
        <Card
          title={
            <span className="flex items-center gap-2 text-xl">
              <ThunderboltOutlined className="text-blue-500" /> {t('homepage.features.title')}
            </span>
          }
          className="overflow-hidden rounded-xl border-none shadow-lg dark:!bg-[#16162a]"
        >
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((feature, index) => (
              <div
                key={index}
                className="flex items-start gap-3 rounded-lg bg-gray-50 p-4 transition-all hover:bg-gray-100 dark:bg-gray-800/50 dark:hover:bg-gray-800"
              >
                <div className="flex-shrink-0">{feature.icon}</div>
                <div>
                  <Text strong className="block dark:text-white">
                    {feature.title}
                  </Text>
                  <Text type="secondary" className="text-sm">
                    {feature.desc}
                  </Text>
                </div>
              </div>
            ))}
          </div>
        </Card>

        {/* Project Structure + Tech Stack */}
        <div className="grid gap-6 md:grid-cols-2">
          {/* Project Structure */}
          <Card
            title={
              <span className="flex items-center gap-2">
                <FolderOutlined /> {t('homepage.projectStructure.title')}
              </span>
            }
            className="overflow-hidden rounded-xl border-none shadow-lg dark:!bg-[#16162a]"
          >
            <div className="font-mono text-sm">
              <div className="space-y-1 text-gray-700 dark:text-gray-300">
                <div>
                  <Text code>src/</Text>
                </div>
                <div className="pl-4">
                  <Text code>├── main/</Text>{' '}
                  <Text type="secondary"># {t('homepage.projectStructure.mainProcess')}</Text>
                </div>
                <div className="pl-8">
                  <Text code>│ ├── ipc/</Text>{' '}
                  <Text type="secondary"># {t('homepage.projectStructure.ipcHandlers')}</Text>
                </div>
                <div className="pl-8">
                  <Text code>│ ├── services/</Text>{' '}
                  <Text type="secondary"># {t('homepage.projectStructure.services')}</Text>
                </div>
                <div className="pl-8">
                  <Text code>│ └── database/</Text>{' '}
                  <Text type="secondary"># {t('homepage.projectStructure.database')}</Text>
                </div>
                <div className="pl-4">
                  <Text code>├── preload/</Text>{' '}
                  <Text type="secondary"># {t('homepage.projectStructure.preload')}</Text>
                </div>
                <div className="pl-4">
                  <Text code>├── renderer/</Text>{' '}
                  <Text type="secondary"># {t('homepage.projectStructure.renderer')}</Text>
                </div>
                <div className="pl-4">
                  <Text code>└── shared/</Text> <Text type="secondary"># {t('homepage.projectStructure.shared')}</Text>
                </div>
              </div>
            </div>
          </Card>

          {/* Tech Stack */}
          <Card
            title={
              <span className="flex items-center gap-2">
                <ToolOutlined /> {t('homepage.techStack.title')}
              </span>
            }
            className="overflow-hidden rounded-xl border-none shadow-lg dark:!bg-[#16162a]"
          >
            <div className="flex flex-wrap gap-2">
              {techStack.map((tech, index) => (
                <span
                  key={index}
                  className="rounded-full bg-blue-100 px-3 py-1.5 text-sm font-medium text-blue-700 dark:bg-blue-900/50 dark:text-blue-300"
                >
                  {tech}
                </span>
              ))}
            </div>
            <Divider className="!my-4" />
            <div className="text-sm text-gray-600 dark:text-gray-400">
              <Paragraph className="!mb-2">{t('homepage.techStack.description1')}</Paragraph>
              <Paragraph className="!mb-0">{t('homepage.techStack.description2')}</Paragraph>
            </div>
          </Card>
        </div>

        {/* Footer */}
        <div className="text-center text-sm text-gray-500 dark:text-gray-400">
          <Text type="secondary">{t('common.madeWith')}</Text>
        </div>
      </div>
    </div>
  );
};
