// src/renderer/pages/UpdateDialog.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useUpdateStore } from '../stores/update'
import { storeToRefs } from 'pinia'
import { ElMessage } from 'element-plus'
import { marked } from 'marked'
import { formatBytes, formatReleaseNotes } from '@/shared/update-types'
import dayjs from 'dayjs'
import WindowControlButtons from '../components/WindowControlButtons.vue'

const { t } = useI18n()
const updateStore = useUpdateStore()
const { status, info, error } = storeToRefs(updateStore)
const isRestarting = ref(false)

onMounted(() => {
  const appName = t('appName')
  document.title = t('update.windowTitle', { appName })
})

watch(error, (err) => {
  if (err) ElMessage.error(t('update.error'))
})

async function handleRestart() {
  if (isRestarting.value) return
  isRestarting.value = true
  try {
    await updateStore.installAndRestart()
  } catch {
    isRestarting.value = false
    ElMessage.error(t('update.error'))
  }
}

function handleClose() {
  window.electron.window.hide()
}

function renderMarkdown(notes: string): string {
  return marked(formatReleaseNotes(notes)) as string
}
</script>

<template>
  <template v-if="status !== 'ready' || !info">
    <div class="flex h-screen items-center justify-center bg-background-primary text-text-secondary">
      {{ t('update.loading') }}
    </div>
  </template>
  <template v-else>
    <div class="flex h-screen flex-col overflow-hidden border border-gray-100 bg-background-primary dark:border-gray-800">
      <!-- Title bar -->
      <div class="titlebar drag flex h-titlebar select-none items-center justify-end px-2 py-2 text-text-primary">
        <WindowControlButtons
          :show-minimize="false"
          :show-maximize="false"
          @close="handleClose"
        />
      </div>

      <!-- Content -->
      <div class="flex min-h-0 flex-1 flex-col p-6 pt-0">
        <!-- Dialog Header -->
        <div class="no-drag mb-2 text-center">
          <div class="mb-2 inline-block rounded-full bg-green-500/10 p-3">
            <el-icon class="text-4xl text-green-500">
              <svg width="1em" height="1em" viewBox="0 0 24 24" fill="none">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" stroke="currentColor" stroke-width="2" />
              </svg>
            </el-icon>
          </div>
          <div>
            <h4 class="m-0 text-lg font-semibold">{{ t('update.title') }}</h4>
            <el-tag type="primary" class="mt-1">
              {{ t('update.newVersion', { version: info.version }) }}
            </el-tag>
          </div>
        </div>

        <el-divider style="margin: 12px 0" />

        <!-- Version Meta -->
        <div class="no-drag mb-4 flex items-center justify-around rounded-lg bg-background-secondary p-3">
          <el-space>
            <el-text class="text-text-secondary">{{ formatBytes(info.files?.[0]?.size || 0) }}</el-text>
          </el-space>
          <el-divider direction="vertical" />
          <el-space>
            <el-text class="text-text-secondary">{{ dayjs(info.releaseDate).format('YYYY-MM-DD') }}</el-text>
          </el-space>
        </div>

        <!-- Release Notes -->
        <div class="no-drag mb-6 flex min-h-0 flex-1 flex-col overflow-hidden rounded-lg border border-gray-200 dark:border-gray-700">
          <div class="border-b border-gray-200 bg-background-secondary px-4 py-2 dark:border-gray-700">
            <el-text tag="strong" size="small" class="uppercase tracking-wider">
              {{ t('update.releaseNotes') }}
            </el-text>
          </div>
          <div class="scrollbar-thin scrollbar-thumb-gray-300 dark:scrollbar-thumb-gray-600 flex-1 overflow-y-auto bg-white/50 p-4 dark:bg-black/10">
            <div
              class="prose prose-sm dark:prose-invert max-w-none text-text-secondary"
              v-html="renderMarkdown(formatReleaseNotes(info.releaseNotes))"
            />
          </div>
        </div>

        <!-- Error -->
        <div
          v-if="error"
          class="no-drag mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-600 dark:bg-red-900/20 dark:text-red-400"
        >
          {{ error }}
        </div>

        <!-- Install Button -->
        <div class="no-drag mt-auto pb-6 pt-4">
          <el-button
            type="primary"
            size="large"
            class="w-full h-12 text-base"
            :loading="isRestarting"
            @click="handleRestart"
          >
            {{ t('update.restartBtn') }}
          </el-button>
          <div class="mt-2 text-center text-xs text-gray-400">{{ t('update.restarting') }}</div>
        </div>
      </div>
    </div>
  </template>
</template>

// src/renderer/pages/Update/UpdateDialog.tsx
import React, { useState, useCallback, useEffect } from 'react';
import { useUpdateSystem } from '../../hooks/useUpdateSystem';
import { Button, Typography, Space, Divider, Tag, message } from 'antd';
import { RocketOutlined, CalendarOutlined, HddOutlined, CheckCircleOutlined } from '@ant-design/icons';
import ReactMarkdown from 'react-markdown';
import dayjs from 'dayjs';
import { formatBytes, formatReleaseNotes } from '@/shared/update-types';
import { WindowControlButtons } from '../../components/WindowControlButtons';
import { useTranslation } from 'react-i18next';

const { Title, Text } = Typography;

const DialogHeader: React.FC<{ version: string }> = ({ version }) => {
  const { t } = useTranslation();
  return (
    <div className="no-drag mb-2 text-center">
      <Space direction="vertical" align="center" size={0}>
        <div className="mb-2 rounded-full bg-green-500/10 p-3">
          <RocketOutlined className="text-4xl text-green-500" />
        </div>
        <div>
          <Title level={4} style={{ margin: 0 }}>
            {t('update.title')}
          </Title>
          <Tag color="blue" className="mt-1">
            {t('update.newVersion', { version })}
          </Tag>
        </div>
      </Space>
    </div>
  );
};

const VersionMeta: React.FC<{ size: number; date: string }> = ({ size, date }) => (
  <div className="no-drag mb-4 flex items-center justify-around rounded-lg bg-background-secondary p-3">
    <Space>
      <HddOutlined className="text-gray-400" />
      <Text type="secondary">{formatBytes(size)}</Text>
    </Space>
    <Divider type="vertical" />
    <Space>
      <CalendarOutlined className="text-gray-400" />
      <Text type="secondary">{dayjs(date).format('YYYY-MM-DD')}</Text>
    </Space>
  </div>
);

const ReleaseNotes: React.FC<{ notes: string }> = ({ notes }) => {
  const { t } = useTranslation();
  return (
    <div className="no-drag mb-6 flex min-h-0 flex-1 flex-col overflow-hidden rounded-lg border border-gray-200 dark:border-gray-700">
      {/* Header / Title Bar */}
      <div className="border-b border-gray-200 bg-background-secondary px-4 py-2 dark:border-gray-700">
        <Text strong className="text-xs uppercase tracking-wider text-text-secondary">
          {t('update.releaseNotes')}
        </Text>
      </div>
      {/* Content Section with Scrollbar */}
      <div className="scrollbar-thin scrollbar-thumb-gray-300 dark:scrollbar-thumb-gray-600 flex-1 overflow-y-auto bg-white/50 p-4 dark:bg-black/10">
        <div className="prose prose-sm dark:prose-invert max-w-none text-text-secondary">
          <ReactMarkdown>{notes || t('update.noDescription')}</ReactMarkdown>
        </div>
      </div>
    </div>
  );
};

export const UpdateDialog: React.FC = () => {
  const { t } = useTranslation();
  const { info, status, error, installAndRestart } = useUpdateSystem();
  const [isRestarting, setIsRestarting] = useState(false);

  useEffect(() => {
    const appName = t('appName');
    document.title = t('update.windowTitle', { appName });
  }, [t]);

  const handleRestart = useCallback(async () => {
    if (isRestarting) return;

    setIsRestarting(true);
    try {
      await installAndRestart();
    } catch {
      setIsRestarting(false);
      message.error(t('update.error'));
    }
  }, [isRestarting, installAndRestart, t]);

  const handleClose = useCallback(() => {
    window.electron.window.hide();
  }, []);

  // Only show when update is ready
  if (status !== 'ready' || !info) {
    return (
      <div className="flex h-screen items-center justify-center bg-background-primary text-text-secondary">
        {t('update.loading')}
      </div>
    );
  }

  return (
    <div className="flex h-screen flex-col overflow-hidden border border-gray-100 bg-background-primary dark:border-gray-800">
      {/* Title bar */}
      <div className="titlebar drag flex h-titlebar select-none items-center justify-end px-2 py-2 text-text-primary">
        <WindowControlButtons showMinimize={false} showMaximize={false} onClose={handleClose} />
      </div>

      {/* Content */}
      <div className="flex min-h-0 flex-1 flex-col p-6 pt-0">
        <DialogHeader version={info.version} />

        <Divider style={{ margin: '12px 0' }} />

        <VersionMeta size={info.files?.[0]?.size || 0} date={info.releaseDate} />

        <ReleaseNotes notes={formatReleaseNotes(info.releaseNotes)} />

        {error && (
          <div className="no-drag mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-600 dark:bg-red-900/20 dark:text-red-400">
            {error}
          </div>
        )}

        <div className="no-drag mt-auto pb-6 pt-4">
          <Button
            type="primary"
            block
            size="large"
            icon={<CheckCircleOutlined />}
            loading={isRestarting}
            onClick={handleRestart}
            style={{ height: '48px', fontSize: '16px' }}
          >
            {t('update.restartBtn')}
          </Button>
          <div className="mt-2 text-center text-xs text-gray-400">{t('update.restarting')}</div>
        </div>
      </div>
    </div>
  );
};
